#服务器端口
server:
  port: 8866
#数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucene?useSSL=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: root
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocations: classpath:mybatis-config.xml 
logging:
  level:
    com.infinova.yimall.mapper: DEBUG